- name: disable nodejs module
  ansible.builtin.command: "dnf module disable nodejs -y"

- name: enable nodejs 20 module
  ansible.builtin.command: "dnf module enable nodejs:20 -y"

- name: install nodejs and mysql client
  ansible.builtin.dnf:
   name: "{{ item }}"
   state: present
  loop:
    - nodejs
    - mysql 

- name: cerate user for backend app
  ansible.builtin.user:
    name: expense

- name: create backend app directory
  ansible.builtin.file:
   path: /app
   state: directory

- name: download backend app code
  ansible.builtin.get_url:
    url: " https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip"
    dest: /tmp/backend.zip

- name: unzip backend app code
  ansible.builtin.unarchive:
   src: /tmp/backend.zip
   dest: /app
   remote_src: yes

- name: install backend app dependencies
  ansible.builtin.command: "npm install"
  args:
   chdir: /app 

- name: copy backend service file
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: installing python mysql dependencies
  ansible.builtin.pip:
    name: 
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: import data into mysql
  community.mysql.mysql_db:
    login_host: "{{ DB_HOST }}"
    login_user: root
    login_password: "{{ login_password }}"
    target: /app/schema/backend.sql
    state: import
    name: all

- name: daemon reload
  ansible.builtin.command: "systemctl daemon-reload"

- name: start backend service
  ansible.builtin.service:
   name: backend
   state: started
   enabled: yes