- name: disable nodejs module
  ansible.builtin.command: "dnf module disable nodejs -y"

- name: enable nodejs 20 module
  ansible.builtin.command: "dnf module enable nodejs:20 -y"

- name: install nodejs and mysql client
  ansible.builtin.dnf:
   name: "{{ item }}"
   state: present
  loop:
    - nodejs
    - mysql 

- name: cerate user for backend app
  ansible.builtin.user:
    name: expense

- name : run app_pre_req from common role
  ansible.builtin.import_role:
    name : common
    tasks_from: app_pre_req

- name: install backend app dependencies
  ansible.builtin.command: "npm install"
  args:
   chdir: /app 

- name: copy backend service file
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: installing python mysql dependencies
  ansible.builtin.pip:
    name: 
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: import data into mysql
  community.mysql.mysql_db:
    login_host: "{{ DB_HOST }}"
    login_user: root
    login_password: "{{ login_password }}"
    target: /app/schema/backend.sql
    state: import
    name: all

- name: daemon reload
  ansible.builtin.command: "systemctl daemon-reload"

- name: start backend service
  ansible.builtin.service:
   name: backend
   state: started
   enabled: yes